source_files = $(wildcard *.c)
object_files = $(source_files:.c=.o)

bw_readmapper: $(object_files)
	cc -o bw_readmapper $(object_files)

clean:
	-rm bw_readmapper
	-rm *.o

depend:
	makedepend $(source_files)
	
# DO NOT DELETE

bw_readmap.o: suffix_array.h /usr/include/stddef.h /usr/include/_types.h
bw_readmap.o: /usr/include/sys/_types.h /usr/include/sys/cdefs.h
bw_readmap.o: /usr/include/sys/_symbol_aliasing.h
bw_readmap.o: /usr/include/sys/_posix_availability.h
bw_readmap.o: /usr/include/machine/_types.h /usr/include/i386/_types.h
bw_readmap.o: /usr/include/sys/_pthread/_pthread_types.h
bw_readmap.o: /usr/include/sys/_types/_null.h
bw_readmap.o: /usr/include/sys/_types/_offsetof.h
bw_readmap.o: /usr/include/sys/_types/_ptrdiff_t.h
bw_readmap.o: /usr/include/machine/types.h /usr/include/i386/types.h
bw_readmap.o: /usr/include/sys/_types/_int8_t.h
bw_readmap.o: /usr/include/sys/_types/_int16_t.h
bw_readmap.o: /usr/include/sys/_types/_int32_t.h
bw_readmap.o: /usr/include/sys/_types/_int64_t.h
bw_readmap.o: /usr/include/sys/_types/_u_int8_t.h
bw_readmap.o: /usr/include/sys/_types/_u_int16_t.h
bw_readmap.o: /usr/include/sys/_types/_u_int32_t.h
bw_readmap.o: /usr/include/sys/_types/_u_int64_t.h
bw_readmap.o: /usr/include/sys/_types/_intptr_t.h
bw_readmap.o: /usr/include/sys/_types/_uintptr_t.h
bw_readmap.o: /usr/include/sys/_types/_rsize_t.h
bw_readmap.o: /usr/include/sys/_types/_size_t.h
bw_readmap.o: /usr/include/sys/_types/_wchar_t.h
bw_readmap.o: /usr/include/sys/_types/_wint_t.h /usr/include/assert.h fasta.h
bw_readmap.o: /usr/include/stdio.h /usr/include/Availability.h
bw_readmap.o: /usr/include/AvailabilityInternal.h
bw_readmap.o: /usr/include/sys/_types/_va_list.h /usr/include/sys/stdio.h
bw_readmap.o: /usr/include/sys/_types/_off_t.h
bw_readmap.o: /usr/include/sys/_types/_ssize_t.h /usr/include/secure/_stdio.h
bw_readmap.o: /usr/include/secure/_common.h fastq.h /usr/include/stdlib.h
bw_readmap.o: /usr/include/sys/wait.h /usr/include/sys/_types/_pid_t.h
bw_readmap.o: /usr/include/sys/_types/_id_t.h /usr/include/sys/signal.h
bw_readmap.o: /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h
bw_readmap.o: /usr/include/i386/signal.h /usr/include/machine/_mcontext.h
bw_readmap.o: /usr/include/i386/_mcontext.h
bw_readmap.o: /usr/include/mach/machine/_structs.h
bw_readmap.o: /usr/include/mach/i386/_structs.h
bw_readmap.o: /usr/include/sys/_pthread/_pthread_attr_t.h
bw_readmap.o: /usr/include/sys/_types/_sigaltstack.h
bw_readmap.o: /usr/include/sys/_types/_ucontext.h
bw_readmap.o: /usr/include/sys/_types/_sigset_t.h
bw_readmap.o: /usr/include/sys/_types/_uid_t.h /usr/include/sys/resource.h
bw_readmap.o: /usr/include/stdint.h /usr/include/_types/_uint8_t.h
bw_readmap.o: /usr/include/_types/_uint16_t.h /usr/include/_types/_uint32_t.h
bw_readmap.o: /usr/include/_types/_uint64_t.h /usr/include/_types/_intmax_t.h
bw_readmap.o: /usr/include/_types/_uintmax_t.h
bw_readmap.o: /usr/include/sys/_types/_timeval.h
bw_readmap.o: /usr/include/machine/endian.h /usr/include/i386/endian.h
bw_readmap.o: /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h
bw_readmap.o: /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h
bw_readmap.o: /usr/include/sys/_types/_ct_rune_t.h
bw_readmap.o: /usr/include/sys/_types/_rune_t.h
bw_readmap.o: /usr/include/sys/_types/_dev_t.h
bw_readmap.o: /usr/include/sys/_types/_mode_t.h /usr/include/string.h
bw_readmap.o: /usr/include/sys/_types/_errno_t.h /usr/include/strings.h
bw_readmap.o: /usr/include/secure/_strings.h /usr/include/secure/_string.h
bw_readmap.o: /usr/include/getopt.h /usr/include/unistd.h
bw_readmap.o: /usr/include/sys/unistd.h
bw_readmap.o: /usr/include/sys/_types/_posix_vdisable.h
bw_readmap.o: /usr/include/sys/_types/_seek_set.h
bw_readmap.o: /usr/include/sys/_types/_gid_t.h
bw_readmap.o: /usr/include/sys/_types/_useconds_t.h /usr/include/sys/select.h
bw_readmap.o: /usr/include/sys/_types/_fd_def.h
bw_readmap.o: /usr/include/sys/_types/_timespec.h
bw_readmap.o: /usr/include/sys/_types/_time_t.h
bw_readmap.o: /usr/include/sys/_types/_suseconds_t.h
bw_readmap.o: /usr/include/sys/_types/_fd_setsize.h
bw_readmap.o: /usr/include/sys/_types/_fd_set.h
bw_readmap.o: /usr/include/sys/_types/_fd_clr.h
bw_readmap.o: /usr/include/sys/_types/_fd_isset.h
bw_readmap.o: /usr/include/sys/_types/_fd_zero.h
bw_readmap.o: /usr/include/sys/_types/_fd_copy.h /usr/include/sys/_select.h
bw_readmap.o: /usr/include/sys/_types/_uuid_t.h /usr/include/gethostuuid.h
fasta.o: fasta.h /usr/include/stdio.h /usr/include/sys/cdefs.h
fasta.o: /usr/include/sys/_symbol_aliasing.h
fasta.o: /usr/include/sys/_posix_availability.h /usr/include/Availability.h
fasta.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
fasta.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
fasta.o: /usr/include/i386/_types.h
fasta.o: /usr/include/sys/_pthread/_pthread_types.h
fasta.o: /usr/include/sys/_types/_va_list.h /usr/include/machine/types.h
fasta.o: /usr/include/i386/types.h /usr/include/sys/_types/_int8_t.h
fasta.o: /usr/include/sys/_types/_int16_t.h
fasta.o: /usr/include/sys/_types/_int32_t.h
fasta.o: /usr/include/sys/_types/_int64_t.h
fasta.o: /usr/include/sys/_types/_u_int8_t.h
fasta.o: /usr/include/sys/_types/_u_int16_t.h
fasta.o: /usr/include/sys/_types/_u_int32_t.h
fasta.o: /usr/include/sys/_types/_u_int64_t.h
fasta.o: /usr/include/sys/_types/_intptr_t.h
fasta.o: /usr/include/sys/_types/_uintptr_t.h
fasta.o: /usr/include/sys/_types/_size_t.h /usr/include/sys/_types/_null.h
fasta.o: /usr/include/sys/stdio.h /usr/include/sys/_types/_off_t.h
fasta.o: /usr/include/sys/_types/_ssize_t.h /usr/include/secure/_stdio.h
fasta.o: /usr/include/secure/_common.h /usr/include/strings.h
fasta.o: /usr/include/string.h /usr/include/sys/_types/_rsize_t.h
fasta.o: /usr/include/sys/_types/_errno_t.h /usr/include/secure/_string.h
fasta.o: /usr/include/secure/_strings.h /usr/include/stdlib.h
fasta.o: /usr/include/sys/wait.h /usr/include/sys/_types/_pid_t.h
fasta.o: /usr/include/sys/_types/_id_t.h /usr/include/sys/signal.h
fasta.o: /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h
fasta.o: /usr/include/i386/signal.h /usr/include/machine/_mcontext.h
fasta.o: /usr/include/i386/_mcontext.h /usr/include/mach/machine/_structs.h
fasta.o: /usr/include/mach/i386/_structs.h
fasta.o: /usr/include/sys/_pthread/_pthread_attr_t.h
fasta.o: /usr/include/sys/_types/_sigaltstack.h
fasta.o: /usr/include/sys/_types/_ucontext.h
fasta.o: /usr/include/sys/_types/_sigset_t.h /usr/include/sys/_types/_uid_t.h
fasta.o: /usr/include/sys/resource.h /usr/include/stdint.h
fasta.o: /usr/include/_types/_uint8_t.h /usr/include/_types/_uint16_t.h
fasta.o: /usr/include/_types/_uint32_t.h /usr/include/_types/_uint64_t.h
fasta.o: /usr/include/_types/_intmax_t.h /usr/include/_types/_uintmax_t.h
fasta.o: /usr/include/sys/_types/_timeval.h /usr/include/machine/endian.h
fasta.o: /usr/include/i386/endian.h /usr/include/sys/_endian.h
fasta.o: /usr/include/libkern/_OSByteOrder.h
fasta.o: /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h
fasta.o: /usr/include/sys/_types/_ct_rune_t.h
fasta.o: /usr/include/sys/_types/_rune_t.h /usr/include/sys/_types/_wchar_t.h
fasta.o: /usr/include/sys/_types/_dev_t.h /usr/include/sys/_types/_mode_t.h
fasta.o: /usr/include/ctype.h /usr/include/runetype.h
fasta.o: /usr/include/sys/_types/_wint_t.h
fastq.o: fastq.h /usr/include/stdio.h /usr/include/sys/cdefs.h
fastq.o: /usr/include/sys/_symbol_aliasing.h
fastq.o: /usr/include/sys/_posix_availability.h /usr/include/Availability.h
fastq.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
fastq.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
fastq.o: /usr/include/i386/_types.h
fastq.o: /usr/include/sys/_pthread/_pthread_types.h
fastq.o: /usr/include/sys/_types/_va_list.h /usr/include/machine/types.h
fastq.o: /usr/include/i386/types.h /usr/include/sys/_types/_int8_t.h
fastq.o: /usr/include/sys/_types/_int16_t.h
fastq.o: /usr/include/sys/_types/_int32_t.h
fastq.o: /usr/include/sys/_types/_int64_t.h
fastq.o: /usr/include/sys/_types/_u_int8_t.h
fastq.o: /usr/include/sys/_types/_u_int16_t.h
fastq.o: /usr/include/sys/_types/_u_int32_t.h
fastq.o: /usr/include/sys/_types/_u_int64_t.h
fastq.o: /usr/include/sys/_types/_intptr_t.h
fastq.o: /usr/include/sys/_types/_uintptr_t.h
fastq.o: /usr/include/sys/_types/_size_t.h /usr/include/sys/_types/_null.h
fastq.o: /usr/include/sys/stdio.h /usr/include/sys/_types/_off_t.h
fastq.o: /usr/include/sys/_types/_ssize_t.h /usr/include/secure/_stdio.h
fastq.o: /usr/include/secure/_common.h /usr/include/strings.h
fastq.o: /usr/include/string.h /usr/include/sys/_types/_rsize_t.h
fastq.o: /usr/include/sys/_types/_errno_t.h /usr/include/secure/_string.h
fastq.o: /usr/include/secure/_strings.h /usr/include/stdlib.h
fastq.o: /usr/include/sys/wait.h /usr/include/sys/_types/_pid_t.h
fastq.o: /usr/include/sys/_types/_id_t.h /usr/include/sys/signal.h
fastq.o: /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h
fastq.o: /usr/include/i386/signal.h /usr/include/machine/_mcontext.h
fastq.o: /usr/include/i386/_mcontext.h /usr/include/mach/machine/_structs.h
fastq.o: /usr/include/mach/i386/_structs.h
fastq.o: /usr/include/sys/_pthread/_pthread_attr_t.h
fastq.o: /usr/include/sys/_types/_sigaltstack.h
fastq.o: /usr/include/sys/_types/_ucontext.h
fastq.o: /usr/include/sys/_types/_sigset_t.h /usr/include/sys/_types/_uid_t.h
fastq.o: /usr/include/sys/resource.h /usr/include/stdint.h
fastq.o: /usr/include/_types/_uint8_t.h /usr/include/_types/_uint16_t.h
fastq.o: /usr/include/_types/_uint32_t.h /usr/include/_types/_uint64_t.h
fastq.o: /usr/include/_types/_intmax_t.h /usr/include/_types/_uintmax_t.h
fastq.o: /usr/include/sys/_types/_timeval.h /usr/include/machine/endian.h
fastq.o: /usr/include/i386/endian.h /usr/include/sys/_endian.h
fastq.o: /usr/include/libkern/_OSByteOrder.h
fastq.o: /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h
fastq.o: /usr/include/sys/_types/_ct_rune_t.h
fastq.o: /usr/include/sys/_types/_rune_t.h /usr/include/sys/_types/_wchar_t.h
fastq.o: /usr/include/sys/_types/_dev_t.h /usr/include/sys/_types/_mode_t.h
suffix_array.o: suffix_array.h /usr/include/stddef.h /usr/include/_types.h
suffix_array.o: /usr/include/sys/_types.h /usr/include/sys/cdefs.h
suffix_array.o: /usr/include/sys/_symbol_aliasing.h
suffix_array.o: /usr/include/sys/_posix_availability.h
suffix_array.o: /usr/include/machine/_types.h /usr/include/i386/_types.h
suffix_array.o: /usr/include/sys/_pthread/_pthread_types.h
suffix_array.o: /usr/include/sys/_types/_null.h
suffix_array.o: /usr/include/sys/_types/_offsetof.h
suffix_array.o: /usr/include/sys/_types/_ptrdiff_t.h
suffix_array.o: /usr/include/machine/types.h /usr/include/i386/types.h
suffix_array.o: /usr/include/sys/_types/_int8_t.h
suffix_array.o: /usr/include/sys/_types/_int16_t.h
suffix_array.o: /usr/include/sys/_types/_int32_t.h
suffix_array.o: /usr/include/sys/_types/_int64_t.h
suffix_array.o: /usr/include/sys/_types/_u_int8_t.h
suffix_array.o: /usr/include/sys/_types/_u_int16_t.h
suffix_array.o: /usr/include/sys/_types/_u_int32_t.h
suffix_array.o: /usr/include/sys/_types/_u_int64_t.h
suffix_array.o: /usr/include/sys/_types/_intptr_t.h
suffix_array.o: /usr/include/sys/_types/_uintptr_t.h
suffix_array.o: /usr/include/sys/_types/_rsize_t.h
suffix_array.o: /usr/include/sys/_types/_size_t.h
suffix_array.o: /usr/include/sys/_types/_wchar_t.h
suffix_array.o: /usr/include/sys/_types/_wint_t.h /usr/include/assert.h
suffix_array.o: /usr/include/strings.h /usr/include/Availability.h
suffix_array.o: /usr/include/AvailabilityInternal.h /usr/include/string.h
suffix_array.o: /usr/include/sys/_types/_errno_t.h
suffix_array.o: /usr/include/sys/_types/_ssize_t.h
suffix_array.o: /usr/include/secure/_string.h /usr/include/secure/_common.h
suffix_array.o: /usr/include/secure/_strings.h /usr/include/stdlib.h
suffix_array.o: /usr/include/sys/wait.h /usr/include/sys/_types/_pid_t.h
suffix_array.o: /usr/include/sys/_types/_id_t.h /usr/include/sys/signal.h
suffix_array.o: /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h
suffix_array.o: /usr/include/i386/signal.h /usr/include/machine/_mcontext.h
suffix_array.o: /usr/include/i386/_mcontext.h
suffix_array.o: /usr/include/mach/machine/_structs.h
suffix_array.o: /usr/include/mach/i386/_structs.h
suffix_array.o: /usr/include/sys/_pthread/_pthread_attr_t.h
suffix_array.o: /usr/include/sys/_types/_sigaltstack.h
suffix_array.o: /usr/include/sys/_types/_ucontext.h
suffix_array.o: /usr/include/sys/_types/_sigset_t.h
suffix_array.o: /usr/include/sys/_types/_uid_t.h /usr/include/sys/resource.h
suffix_array.o: /usr/include/stdint.h /usr/include/_types/_uint8_t.h
suffix_array.o: /usr/include/_types/_uint16_t.h
suffix_array.o: /usr/include/_types/_uint32_t.h
suffix_array.o: /usr/include/_types/_uint64_t.h
suffix_array.o: /usr/include/_types/_intmax_t.h
suffix_array.o: /usr/include/_types/_uintmax_t.h
suffix_array.o: /usr/include/sys/_types/_timeval.h
suffix_array.o: /usr/include/machine/endian.h /usr/include/i386/endian.h
suffix_array.o: /usr/include/sys/_endian.h
suffix_array.o: /usr/include/libkern/_OSByteOrder.h
suffix_array.o: /usr/include/libkern/i386/_OSByteOrder.h
suffix_array.o: /usr/include/alloca.h /usr/include/sys/_types/_ct_rune_t.h
suffix_array.o: /usr/include/sys/_types/_rune_t.h
suffix_array.o: /usr/include/sys/_types/_dev_t.h
suffix_array.o: /usr/include/sys/_types/_mode_t.h /usr/include/stdio.h
suffix_array.o: /usr/include/sys/_types/_va_list.h /usr/include/sys/stdio.h
suffix_array.o: /usr/include/sys/_types/_off_t.h /usr/include/secure/_stdio.h
